/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progoti.scanner;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.List;

/**
 *
 * @author Shaown
 */
public class CounterGui extends javax.swing.JFrame {

    /**
     * Creates new form CounterGui
     */
    public CounterGui() {
        initComponents();
        countTextField.setEditable(false);
        countTextField.setHorizontalAlignment(SwingConstants.CENTER);
        dsRadioButton.setSelected(true);
        addButtonGroup();
        setSrcDir();
        setActionListenerToRadioButtons();
        this.setTitle("Scanner File Counter");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resetButton = new javax.swing.JButton();
        countButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dsRadioButton = new javax.swing.JRadioButton();
        kycRadioButton = new javax.swing.JRadioButton();
        dsDirButton = new javax.swing.JButton();
        kycDirButton = new javax.swing.JButton();
        dsDirTextField = new javax.swing.JTextField();
        kycDirTextField = new javax.swing.JTextField();
        countTextField = new javax.swing.JTextField();
        lastFileNameTextField = new javax.swing.JTextField();
        headerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resetButton.setText("Reset");
        resetButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        countButton.setText("Count");
        countButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                countButtonActionPerformed(evt);
            }
        });

        dsRadioButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                dsRadioButtonActionPerformed(evt);
            }
        });

        dsDirButton.setText("DS");
        dsDirButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                dsDirButtonActionPerformed(evt);
            }
        });

        kycDirButton.setText("KYC");
        kycDirButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                kycDirButtonActionPerformed(evt);
            }
        });

        dsDirTextField.setEditable(false);

        kycDirTextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dsDirTextField)
                    .addComponent(kycDirTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kycDirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dsDirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dsRadioButton)
                    .addComponent(kycRadioButton))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dsRadioButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dsDirButton)
                        .addComponent(dsDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kycRadioButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kycDirButton)
                        .addComponent(kycDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        countTextField.setEditable(false);
        countTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        countTextField.setForeground(new java.awt.Color(255, 51, 0));
        countTextField.setText("0");
        countTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                countTextFieldActionPerformed(evt);
            }
        });

        lastFileNameTextField.setEditable(false);

        headerLabel.setText("Last Modified File Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addComponent(countButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(countTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(countTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dsRadioButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_dsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsRadioButtonActionPerformed

    private void dsDirButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_dsDirButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Select Directory");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.setCurrentDirectory(new File("."));
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.showOpenDialog(this);
        
        if(jFileChooser.getSelectedFile() != null){
            File selectedDSDir = jFileChooser.getSelectedFile();
            dsDirTextField.setText(selectedDSDir.getAbsolutePath());
            dsDirTextField.setEditable(false);
            Utility.writeToFile("ds:" + selectedDSDir.getAbsolutePath(), true, false);

        }
    }//GEN-LAST:event_dsDirButtonActionPerformed

    private void kycDirButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_kycDirButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Select Directory");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.setCurrentDirectory(new File("."));
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.showOpenDialog(this);
        
        if(jFileChooser.getSelectedFile() != null){
            File selectedDSDir = jFileChooser.getSelectedFile();
            kycDirTextField.setText(selectedDSDir.getAbsolutePath());
            kycDirTextField.setEditable(false);
            Utility.writeToFile("kyc:" + selectedDSDir.getAbsolutePath(), false, false);
        }
    }//GEN-LAST:event_kycDirButtonActionPerformed

    private void resetButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        String value = "";
        if(dsRadioButton.isSelected()){
            value = Utility.writeToFile("", true, true);
        } else if(kycRadioButton.isSelected()){
            value = Utility.writeToFile("", false, true);
        }
        countTextField.setText(String.valueOf(0));
        lastFileNameTextField.setText(value);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void countButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
        // TODO add your handling code here:
        if(dsRadioButton.isSelected()){
            countTextField.setText(String.valueOf(Utility.getLatestCountFile(true)));
        } else if(kycRadioButton.isSelected()){
            countTextField.setText(String.valueOf(Utility.getLatestCountFile(false)));
        }
    }//GEN-LAST:event_countButtonActionPerformed

    private void countTextFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_countTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CounterGui().setVisible(true);
            }
        });
    }

    private javax.swing.JButton countButton;
    private javax.swing.JTextField countTextField;
    private javax.swing.JButton dsDirButton;
    private javax.swing.JTextField dsDirTextField;
    private javax.swing.JRadioButton dsRadioButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kycDirButton;
    private javax.swing.JTextField kycDirTextField;
    private javax.swing.JRadioButton kycRadioButton;
    private javax.swing.JTextField lastFileNameTextField;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

    private void addButtonGroup() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(dsRadioButton);
        buttonGroup.add(kycRadioButton);
    }

    private void setSrcDir() {
        List<String> dirNameList = Utility.getStringListFromFileName();
        if(dirNameList.size() == 1){
            setValueToTextField(dirNameList.get(0));
        } else if(dirNameList.size() == 2){
            setValueToTextField(dirNameList.get(0));
            setValueToTextField(dirNameList.get(1));
        }
    }
    
    private void setValueToTextField(String value){
        if(value.contains("kyc")){
            value = value.substring(value.indexOf(":")+1).trim();
            kycDirTextField.setText(value);
        } else if(value.contains("ds")){
            value = value.substring(value.indexOf(":")+1).trim();
            dsDirTextField.setText(value);
        }
    }

    private void setActionListenerToRadioButtons() {
        dsRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lastFileNameTextField.setText(Utility.latestDSFileName);
            }
        });
        kycRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lastFileNameTextField.setText(Utility.latestKYCFileName);
            }
        });
        
    }
}
